# -*- coding: utf-8 -*-
"""KNN_iris_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEL0wHTQV5WqJiXLnWGFvxNooUFsH7R-
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, confusion_matrix

iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

X_test.shape

for j in range(10,120,5):
  knn = KNeighborsClassifier(n_neighbors=j)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  print(j, accuracy_score(y_test, y_pred).round(4)*100)

